### ISSUE TITLE
What is the best system instruction?

### ISSUE THREAD

**Issue by gonzalu** [stavsap/comfyui-ollama#60]
Trying to find the best System Instruction to generate prompts for Flux.1 Dev or other similar models using T5XXL and CLIP_L 

Thank you.

**Comment by stavsap** [comment]
there is no silver bullet for this one, just play and experiment

**Comment by gonzalu** [comment]
Do you have some examples you can share at least? Or point me to a resource that has examples? 

Thank you.

**Comment by qskousen** [comment]
I came across this closed issue in my search, and just wanted to add something here for posterity.

Be aware that the system prompt is HIGHLY dependent on what sort of image prompt you want (Flux, SDXL, Pony, etc.) as well as the Ollama model you are querying. That said, this one is quite flexible gives me reliable tag-style prompts with the Ollama Generate V2 node, using Gemma3 model in Ollama. I then join this with some predefined style tags like `4k, absurdres, masterpeice,` etc. with a text concat node.

```
You are an image deck slide generator.

Be concise. Generate tags seperated by commas, such as with a danbooru image. Be creative. Use tags to describe the image, features of the image, framing, and tone, as well as details of any people that may be in the image and their poses, actions, and facial expressions. If no user input is provided, create a random prompt.

You MUST respond ONLY with the tags of the prompt, no commentary or explanation or questions. This is very important!
```

The user prompt can't actually be blank, so in order to get a random one I enter a single space character.
