### ISSUE TITLE
how to free gpu used

### ISSUE THREAD

**Issue by Chengym2023** [stavsap/comfyui-ollama#66]
i use ollama for flux ,and flux is large,so is there a way to clean gpu used or some method to free ?

**Comment by stavsap** [comment]
clean gpu usage after using ollama node?

**Comment by Chengym2023** [comment]
> clean gpu usage after using ollama node?

yes. 4070TIS,use flux and ollama model,sometimes out of memory

**Comment by inferno46n2** [comment]
Yes please for the love of god add .to("cpu") in the code for the model at end but then also have to add moving back to gpu before it does it's thing or it will fail on 2nd run

This is very lazy memory management on your end. Keeping ~11gb VRAM loaded is unusable

**Comment by stavsap** [comment]
@inferno46n2 do i work for you?

**Comment by inferno46n2** [comment]
> @inferno46n2 do i work for you?

Not with code like this you don’t

**Comment by stavsap** [comment]
🤣😂, feel free to share your god coding skills with all of us and make a PR to handle this.

**Comment by inferno46n2** [comment]
> 🤣😂, feel free to share your god coding skills with all of us and make a PR to handle this.

Already told you how to handle it

**Comment by stavsap** [comment]
Your comment don't make any sense and 0 understanding on what the nodes do. Move on child.

**Comment by stavsap** [comment]
@Chengym2023 By the way, you can have this behavior by setting keet_alive = 0 in the node. ollama will remove the model after usage. make an update I change the keep alive to work with step 1 instead of 5 so you can set it to 0 now.

**Comment by Symbiomatrix** [comment]
To whom it may concern, I have determined that if you run a simple workflow doing nothing (eg string constant -> show text), it'll unload the main (flux) model instantly. I like to use [rgthree's group bypasser](https://github.com/rgthree/rgthree-comfy) node to quickly deselect the main gen group nodes. Another option is [kjnodes debug vram](https://github.com/kijai/ComfyUI-KJNodes), but it always unloads everything.
Regarding @inferno46n2 's request, this is very tricky: Comfy seems to connect any model operations with a gen (down to the image output level), defaulting to unload if no gen happens. My best workaround is this: First, get [multigpu nodes](https://github.com/pollockjj/ComfyUI-MultiGPU) in order to be able to select unet being loaded to gpu or cpu. Then, create a dummy gen group, containing only: unetloader with device=cpu, dualclip as usual, empty conditioning, empty latent of 64x64, 1 step. Running this will move the existing model to cpu provided it's the same model, no disk access. (I'm thinking of make a "coalesce" node to be able to select either cuda:0 / cpu when main is disabled, haven't been able to find something like that).

There are a few big caveats:
- Moving from gpu to cpu is a very heavy operation for me: It takes ~1-2 minutes (~400mbps), and fills up ~30gb of ram before falling back to ~20gb. Would not recommend without at least 48gb of ram. Conversely, reloading cpu-gpu is fast, a matter of seconds.
- You MUST connect the same cliploader node to both the main and dummy workflow. Connecting a different node with the same models will result in reloading these from disk. Possibly an issue with change detection or how multigpu caches things.
- Running the dummy workflow, at least with flux, yields multiple errors for me upon reaching the sampler, which I have listed in [this issue](https://github.com/pollockjj/ComfyUI-MultiGPU/issues/44). The offload works fine, provided you either run it separately or force the run order as unetloader offload -> ollama -> rest of dummy sampling using fake switches, but it would appear that if you run ollama after offload and then go back to main, it'll reload from disk (not sure if the whole model).

So, looks like the easiest way for now is to just unload and keep the flux checkpoint on a fast nvme ssd.
